version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    # - gofmt
    # - goimports
    # - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 140
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

formatters:
  gofmt:
    command: gofmt
    args: ["-w", "."]
  goimports:
    command: goimports
    args: ["-w", "."]

issues:
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
