apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  name: p1
spec:
  clusterRef: c1
  enabled: true
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: leaf
    - matchLabels:
        vendor: Nokia
        role: spine
  subscriptionSelectors:
    - matchLabels:
        vendor: Nokia
        group: interface_metrics
    - matchLabels:
        vendor: Nokia
        group: bgp_metrics
    - matchLabels:
        vendor: Nokia
        group: lldp_metrics
  outputs:
    outputSelectors:
      - matchLabels:
          type: metrics
