apiVersion: operator.gnmic.dev/v1alpha1
kind: Pipeline
metadata:
  name: p2
spec:
  clusterRef: c1
  enabled: true
  targetSelectors:
    - matchLabels:
        vendor: Nokia
        role: leaf
    - matchLabels:
        vendor: Nokia
        role: spine
  subscriptionSelectors:
    - matchLabels:
        vendor: Nokia
        group: interface_state
    - matchLabels:
        vendor: Nokia
        group: bgp_state
    - matchLabels:
        vendor: Nokia
        group: lldp_state
  outputs:
    outputSelectors:
    - matchLabels:
        type: mq
