---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-peppers
  namespace: netbox
data: 
  # please change `openssl rand -hex 32`
  peppers.yaml: |-
    API_TOKEN_PEPPERS:
      1: '4250726b8f643bd059b7cdc65eb411119d9f1e034a7961c80d3ba04eaf1186de'
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-superuser
  namespace: netbox
type: Opaque
stringData:
  username: "admin"
  email: "admin@example.com"
  password: "netbox" # please change
  api_token: "0123456789abcdef0123456789abcdef01234567"