// Package apiserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiserver

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	SignatureScopes  = "signature.Scopes"
)

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	// Debounced True when this call did not schedule a new run because one was requested within the debounce window.
	Debounced bool `json:"debounced"`

	// RequestedAt When a run was last requested through this endpoint.
	RequestedAt time.Time `json:"requestedAt"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Request an immediate discovery run for a TargetSource.
	// (POST /api/v1/namespaces/:namespace/targetsources/:name/refresh)
	RefreshTargetSource(c *gin.Context)
	// Get cluster plan.
	// (GET /clusters/:namespace/:name/plan)
	GetClusterPlan(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RefreshTargetSource operation middleware
func (siw *ServerInterfaceWrapper) RefreshTargetSource(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	c.Set(SignatureScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshTargetSource(c)
}

// GetClusterPlan operation middleware
func (siw *ServerInterfaceWrapper) GetClusterPlan(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterPlan(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/namespaces/:namespace/targetsources/:name/refresh", wrapper.RefreshTargetSource)
	router.GET(options.BaseURL+"/clusters/:namespace/:name/plan", wrapper.GetClusterPlan)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVTW8bNxD9KwO2QIFA3lWUpAcVOahumwRFPhAbaAHbh9FyVst4xWGGs1YWgf57Qa60",
	"kiWj6Km3/SA5772Z9/jdVLwO7MlrNPPvJlYNrTE/fqZaKDafKQb2kdKnIBxI1FFeYGnJna/IDi+xEhfU",
	"sTdzcy0dwaYhD9q4CBW2LVhnwbNCKmG7lgDB0wak87CkCrtIwJ5ggxGEvnYUlSxsnDYunUKwLwcb5y1v",
	"CjMx2gcyc7Nkbgm92U7MuHOh56j+SoAwV0xVWox6VEob4W7VDIjJ28DOa6pSs6xRzdxYVLpQt6ZD6aji",
	"/Mpsd6WdJDVuHsGYHAl1N27k5ReqNG+MVHXitL9K2g/SLgmFZNFpc87iktcBhSw4DxX7qOgVEirAFTof",
	"Nat1RZWQgsc1WVj2EANVxYaWDfN9gZ02xVAjEcxNz0LmTwd2jWpIqka38qid0Dmat/QN3r5fXALXue6O",
	"OSzZ9hPgvAzbtocgVLtvu5bCrYkNzl79/PrWAMvw+ur57PWtmcA99QPm/8ZjBJeouISpIbSZRtpl5ubv",
	"i7fM9xdXI4uRIAb3J/Vmm9rgfM2Jnzpt07/Vh/fvKvgYSFBZ4PPvV9ew+PTOTMwDSRzYT4tpMUsKcSCP",
	"wZm5eVFMixdmYgJqk3tZYnDlw/MygYkBK4rlfHwuFWVFGrmT8Ucpg/Oy4zg+McgfWF3dX7Bv+wKuG8pq",
	"Q4UijiJ4huFUsKj4CzgFFyEtBvTgfOgUlGHUDR5IXO0qTKcXsIDYVRXFWHft4Fz0nhWVYu7IdT77KiMG",
	"9DZ/rNircNuSQCBJjompGIt1HqWHumvbZLwCLrFt47Gvj8/7KcK+tyd2389XEHpw3MWcFSgEWN173rRk",
	"V7vZ4m7MGOdXgJ61IcnFb73JrZJM9Z01833KHYMwY4z8yrZP6id25HMjnpXPDjmZnsZ0WGamT0TDdnLS",
	"vo8Bv3ZUwB8sGxSbsocHEx13YsjPQ5fSsKdGVuxrt+qEbDEk3pDPedZm0+kJXgyh3R1Yfomp/DH4H4Vq",
	"Mzc/lIdboNxdAeVp/j9B5Ld9sM2PYvWQqC3FNDLoz5uKK07gZ9PZ/4l3cQ4yoXg5fX7usRS+5HXfjBpd",
	"u1/98okL79QYlrMTFeibi5oyrsFszZ0UQB6X+cSjG8DMbx5n/83ddvL9OH5v7rZ3ExO79TrNWhrfIW6T",
	"sddrsg6VwLpY8QNJn+nWLICPwBW5aFm1XVSSR3E0BFBoMQu/otyTx455Q3o57PyUlj09gSdX1mE9CGkn",
	"/l+k/MCQ6udRx+TjzCDfyrtzBs1GDd6Qwo5L3pnobbf/BAAA//+iRWvV2ggAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
