// Package apiserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiserver

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for TargetOperation.
const (
	Created TargetOperation = "created"
	Deleted TargetOperation = "deleted"
	Updated TargetOperation = "updated"
)

// Valid indicates whether the value is a known member of the TargetOperation enum.
func (e TargetOperation) Valid() bool {
	switch e {
	case Created:
		return true
	case Deleted:
		return true
	case Updated:
		return true
	default:
		return false
	}
}

// Label Label must be passed as key:value pair. Multiple values per key possible
type Label struct {
	// Key key value, e.g. vendor
	Key *string `json:"key,omitempty"`

	// Value value, e.g. srlinux
	Value *string `json:"value,omitempty"`
}

// Target defines model for Target.
type Target struct {
	// Address IPv4 or IPv6
	Address *string `json:"address,omitempty"`

	// Labels Input of labels through key:value pair
	Labels *[]Label `json:"labels,omitempty"`

	// Name Routername
	Name string `json:"name"`

	// Operation Either created, updated or deleted. created and updated internally is the same operation (apply)
	Operation TargetOperation `json:"operation"`

	// Port gNMIc port
	Port *int `json:"port,omitempty"`

	// TargetProfile TargetProfile applied to specific router
	TargetProfile *string `json:"targetProfile,omitempty"`
}

// TargetOperation Either created, updated or deleted. created and updated internally is the same operation (apply)
type TargetOperation string

// Targets defines model for Targets.
type Targets = []Target

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ApplyTargetsJSONRequestBody defines body for ApplyTargets for application/json ContentType.
type ApplyTargetsJSONRequestBody = Targets

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Targets received are applied in gNMIc Operator.
	// (POST /api/v1/:namespace/target-source/:name/applyTargets)
	ApplyTargets(c *gin.Context)
	// Get cluster plan.
	// (GET /clusters/:namespace/:name/plan)
	GetClusterPlan(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ApplyTargets operation middleware
func (siw *ServerInterfaceWrapper) ApplyTargets(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyTargets(c)
}

// GetClusterPlan operation middleware
func (siw *ServerInterfaceWrapper) GetClusterPlan(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetClusterPlan(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/:namespace/target-source/:name/applyTargets", wrapper.ApplyTargets)
	router.GET(options.BaseURL+"/clusters/:namespace/:name/plan", wrapper.GetClusterPlan)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFRNj9s2EP0rg2kPLaBK3iboQbdtEQQGmtZI9rbYAy2NbWYpkp0ZGjUC//eCpOqP2AVy6U3mfL15742/",
	"4BCmGDx5Fey/oAw7mkz5/N2syeWPkWRgG9UGj319himJwpogGhEawQi80qHfG5fym+UWPiSnNjqC8igQ",
	"iXMOxCBi146wwcghEqulMu+VDrfTckVp0AC12xb25MfA2KAeImGPomz9Fo8NlqzbBpfFws769Pdt9fH0",
	"EtafadDc78nwljQ3vIZpxpFJ5HbScrV/C4Fhudr/cg+gy8Tdq/MxKYQN1ATQHYe03X1FKDZolaZS/z3T",
	"Bnv8rjtr183CdVW180KG2Rzyb2+mO/R8DEmJS+wO5Ly3qZlfF76zuiOGgckojQ2kOOaPTMBIjpTG9t8g",
	"GD+e4taXec4dwOZdCcRMBKdJ8IOJ0R1+xAbJpwn7Z5zbYINzE2xwnoEvd1DHwHoLePvHh+UAJXaqyWC2",
	"xIWuIveKw8a6Ozw9XYYhQ7Q0ggaQSIPd2AG4MHnXW0x/Jcs05mVmqm3ES3pf/tOARfBvUn427I30xwaF",
	"hsRWD59yarXxmgwTPybdnc4+19Tn8xY71YjH3MP6TcipajUTNPP5Z1khMHx89+kJHldLbHBPLJW1Rbto",
	"H2YjeRMt9vimXbRv8u0b3RUgnYm22z90fWZGohmoq1r8JCHxQDXQFVdcUBKDFJFPHC5H7PHxMqsST6K/",
	"hrH8tQzBK/lSVhQcSmH3WarBK5HfRrNUUs7KKicqDxKDl8rxz4uH/2fsPW/KyZWShoFENsm5cvlvK4zr",
	"oseSAxpeyedLnKyI9dt8v9bvjbPjlXOwf772zPPL8aVBSdNk+HABgmkgu89Hz+c7sR6u7dKW5t3gkiix",
	"XIpf5Y7OFHLmv+Brld+T/lYrVznthvXF7boX+cCkiT3NC542eE8KMyDI4zPG4/GfAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
