apiVersion: operator.gnmic.dev/v1alpha1
kind: Subscription
metadata:
  name: sub2
  labels:
    vendor: nokia_srlinux
    group: interface_state
spec:
  paths:
    - /interface
    - /interface/subinterface
  mode: STREAM/ON_CHANGE
  encoding: PROTO
  depth: 1
