openapi: 3.0.3
info:
  title: "gNMIc Operator REST API"
  version: "0.0.1"
paths:
  /clusters/:namespace/:name/plan:
    get:
      summary: "Get cluster plan."
      operationId: "getClusterPlan"
      responses:
        '200':
          description: "ClusterPlan returned"
  /api/v1/:namespace/target-source/:name/applyTargets:
    post:
      summary: "Interface for real-time target updates, usually using a webhook. Targets are applied in the gNMIc Operator."
      operationId: "applyTargets"
      security:
        - bearerAuth: []
          signature: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Targets'
      responses:
        '201':
          description: "Targets applied successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Targets'
        '401':
          description: Access token is missing or invalid

components:
  schemas:
    Targets:
      type: array
      items:
        $ref: '#/components/schemas/Target'
    Label:
      description: TBD
      type: object
      additionalProperties:
        description: Label must be passed as key:value pair, multiple values per key possible.
        type: string
    Target:
      description: Network device to be monitored. Properties not marked as optional must be in JSON body.
      type: object
      required:
        - name
        - address
        - operation
      properties:
        name:
          type: string
          description: Name of device to be monitored.
        address:
          type: string
          description: IPv4/IPv6 address or hostname.
        port:
          type: integer
          description: gNMIc port.
        targetProfile:
          type: string
          description: TargetProfile applied to apply to this router.
        labels:
          type: array
          description: Input of labels as key:value pair.
          items:
            $ref: '#/components/schemas/Label'
        operation:
          type: string
          enum:
            - created
            - updated
            - deleted
          description: "Either `created`, `updated` or `deleted`. `created` and `updated` are identical and both apply the target."
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: HTTP authentication using Bearer token
    signature:
      name: X-Hook-Signature
      type: apiKey
      in: header
      description: HMAC signature of the request payload
      