# docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate  -c /local/docs/content/docs/advanced/openapi-generator-config.yaml

generatorName: markdown
inputSpec: /local/internal/apiserver/openapi.yaml
outputDir: /local/docs/content/docs/advanced/rest-api-documentation
templateDir: /local/docs/content/docs/advanced/openapi-templates
files:
  _index.mustache:
    destinationFilename: _index.md
  apis.mustache:
    destinationFilename: Apis/DefaultAPI.md
  models.mustache:
    destinationFilename: Models/Target.md