# docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate  -c /local/docs/content/docs/advanced/openapi-generator-config.yaml

generatorName: markdown
inputSpec: /local/docs/content/docs/advanced/openapi.yaml
outputDir: /local/docs/content/docs/advanced/rest-api-documentation
templateDir: /local/docs/content/docs/advanced/openapi-templates/markdown-documentation
files:
  README.mustache:
    destinationFilename: _index.md