apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetSource
metadata:
  name: http-discovery
spec:
  provider:
    http:
      url: http://inventory-service:8080/targets
  labels:
    source: inventory
  type: http
  profile: eos