apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetSource
metadata:
  name: http-discovery
spec:
  provider:
    http:
      url: http://srbsci-121:8081/api/dcim/devices/?export=test
      token: nbt_PtTwUBOtEvm7.64263351281a7a34227c81e6c083c7b1ff71447348c92f5821cc2088462320f1
  labels:
    source: inventory
  type: http
  profile: eos