apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetSource
metadata:
  name: pull-loader
spec:
  provider:
    pull:
      url: http://inventory-service:8080/targets
  labels:
    source: inventory
  type: pull
  profile: eos