apiVersion: operator.gnmic.dev/v1alpha1
kind: TargetSource
metadata:
  name: http-discovery
spec:
  provider:
    http:
      url: http://srbsci-121:8081/api/dcim/devices/?export=test
  webhook:
    enabled: true
  targetLabels:
    source: inventory
    site: siteA
    tags: "inventory,siteA,http-discovery"
  restartPolicy:
    maxRestarts: 2
    backoffSeconds: 4
  targetProfile: eos